Support for Node 15
namics/webpack-concat-text-plugin pull request #13
Opened 2021-03-29 21:16 UTC by manuelaguirre

2021-03-29 21:20 UTC, manuelaguirre commented
I extended the previous PR with what you asked its author

2021-04-01 10:44 UTC, zidizei requested changes
Thanks for picking this up! I've added some minor change suggestions to your PR. Once that's been taken care of, we can get this thing on the road! 😃

2021-04-01 10:44 UTC, zidizei commented on .github/workflows/publish.yml
> +        node: [12, 15]
Please leave in the test matrix value for Node 14. Same goes for the matrices in `test.yml`.

```suggestion
        node: [12, 14, 15]
```

2021-04-01 10:44 UTC, zidizei commented on package.json
> +  "version": "0.1.10",
We don't need to specify the version manually in the PR. This value will be updated once we prepare this for a release.

2021-05-05 08:56 UTC, zidizei commented
Superseded by #16

2021-05-05 08:56 UTC, closed without merging